stages:
  - test
  - build
  - deploy

image: node:18
before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm install # install dependencies
cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

test:
  stage: test
  script:
    - pnpm build:packages
    - pnpm build:examples
    - pnpm prettier
    - pnpm eslint
    - pnpm tsc
    - pnpm check:types
    - pnpm test

build-docs:
  stage: build
  script:
    - pnpm build:packages
    - pnpm build:docs
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  script:
    - mv docs public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
