stages:
  - test
  - comment
  - build
  - release
  - deploy

image: node:18
before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm install # install dependencies
cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

gemnasium-dependency_scanning:
  variables:
    DS_INCLUDE_DEV_DEPENDENCIES: "false"

test:
  stage: test
  script:
    - pnpm build:packages
    - pnpm build:examples
    - pnpm prettier
    - pnpm eslint
    - pnpm tsc
    - pnpm check:types
    - pnpm test

comment:
  stage: comment
  # Commenting on merge to canary isn't ideal, but there seems to be a long
  # standing bug that prevents protected variables from being made available
  # to MRs even between two protected branches. Hopefully this will give us
  # a way to cross check changesets while still keeping variables protected.
  only:
    - canary
    - main
  script: pnpm changesets-gitlab comment # comment automatically like https://github.com/changesets/bot

build-docs:
  stage: build
  script:
    - pnpm build:packages
    - pnpm build:docs
  artifacts:
    paths:
      - docs

release:
  only:
    - main
  script: pnpm changesets-gitlab
  variables:
    INPUT_PUBLISH: pnpm changeset publish

pages:
  stage: deploy
  script:
    - mv docs public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
