stages:
  - test

image: node:18
before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm install # install dependencies
cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

test:
  stage: test
  script:
    - pnpm build:packages
    - pnpm build:examples
    - pnpm prettier
    - pnpm eslint
    - pnpm tsc
    - pnpm check:types
    - pnpm test
